name: thanapob_desoler
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^11.1.2
  just_audio: ^0.9.35
  font_awesome_flutter: ^10.4.0
  audio_session: ^0.1.16
  just_audio_windows: ^0.2.0
  audioplayers: ^4.1.0
  animated_text_kit: ^4.2.2
  syncfusion_flutter_sliders: ^23.1.39

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/songs/
    - assets/images/
